-- SOLO PostgreSQL del backend. Nunca ejecutar en SAP.
-- Requiere respaldo verificado, puente pausado y backend detenido.
-- Conserva api_keys y _prisma_migrations; elimina operadores y configuracion.
BEGIN;
SET LOCAL lock_timeout = '5s';
TRUNCATE TABLE
  public."grupos_productos",
  public."bodegas",
  public."listas_precios",
  public."vendedores",
  public."proveedores",
  public."productos",
  public."productos_precios",
  public."productos_existencias",
  public."productos_codigos_barras",
  public."confirmaciones_etiquetas_picking",
  public."unidades_medida",
  public."clientes",
  public."facturas",
  public."facturas_lineas",
  public."pedidos",
  public."pedidos_lineas",
  public."entregas",
  public."entregas_lineas",
  public."notas_credito",
  public."notas_credito_lineas",
  public."pagos",
  public."pagos_facturas",
  public."entradas_mercancias",
  public."entradas_mercancias_lineas",
  public."traslados_inventario",
  public."traslados_inventario_lineas",
  public."sincronizaciones",
  public."sincronizaciones_lotes",
  public."errores_sincronizacion",
  public."auditoria",
  public."picking_pedidos",
  public."picking_pedidos_lineas",
  public."picking_escaneos",
  public."operadores",
  public."sesiones_operador",
  public."sincronizacion_estados",
  public."inventario_productos",
  public."inventario_cajas",
  public."inventario_movimientos",
  public."sincronizacion_recorridos",
  public."inventario_pequena_lotes",
  public."inventario_descuentos",
  public."documentos_stock",
  public."documentos_stock_lineas",
  public."configuracion",
  public."inventario_operaciones"
RESTART IDENTITY RESTRICT;
COMMIT;
